---
title: "Math 420 Final Project"
author: "Riley Coburn"
date: "12/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(10)
runs <- 100000

xs <- runif(runs,min=-0.5,max=0.5) #uniform distribution
ys <- runif(runs,min=-0.5,max=0.5) #uniform distribution

#we are randomly sampling from two uniform distributions

in.circle <- xs^2 + ys^2 <= 0.5^2 #calculating test statistic i.e. whether a randomly sampled point from our uniform distributions falls within the circle inscribed in the sampling distribution

#Empirically, A_square = (2r)^2 = 4r^2. Suppose we don't know a value for pi, but instead just know that A_circle is proportional to r^2. That is A_circle = cr^2. If we were to 

mc.pi <- (sum(in.circle)/runs)*4 #Finding proportion of points of the square that lie within the circle. We multiply by a factor of 4 because the proportion of areas is A_square/A_circle = 4r^2/cr^2 = 4/c meaning c = 4*A_circle/A_square. Here, A_cirle is just the number of points that we have inside the circle and A-square is just all points as the sampling distribution is a square. 
plot(xs,ys,pch='.',col=ifelse(in.circle,"blue","grey")
     ,xlab='',ylab='',asp=1,
     main=paste("MC Approximation of Pi =",mc.pi))
```

